services:
    dev:
        container_name: server-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        ports:
            - ${PORT}:${PORT}
        tty: true
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/app/node_modules
            - ssh-data:/root/.ssh
        networks:
            - server-network
        environment:
            - DB_HOST=db
    db:
        container_name: server-db
        image: postgres:16.6-alpine3.21
        ports:
            - ${DB_PORT}:${DB_PORT}
        tty: true
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always
        networks:
            - server-network
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
    pgadmin4:
        container_name: server-pgadmin
        image: dpage/pgadmin4
        ports:
            - ${PGADMIN_PORT}:80
        tty: true
        volumes:
            - pgadmin4-data:/var/lib/pgadmin
        restart: always
        networks:
            - server-network
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
            - PGADMIN_CONFIG_SESSION_EXPIRATION_TIME=365
            - PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME=60
        extra_hosts:
            - host.docker.internal:host-gateway

volumes:
    ssh-data:
    node_modules:
    db-data:
    pgadmin4-data:

networks:
    server-network:
